using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Net;
using System.Diagnostics;

namespace GTPSAutoSet
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.Title = "GTPSAutoSet";
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . ");
            Console.ResetColor();
            Console.ReadKey();
            Console.Write("\n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Turn off the Windows Firewall Defender...");
            Process proc = new Process();
            string top = "netsh.exe";
            proc.StartInfo.Arguments = "Advfirewall set privateprofile state off";
            proc.StartInfo.FileName = top;
            proc.StartInfo.UseShellExecute = false;
            proc.StartInfo.RedirectStandardOutput = true;
            proc.StartInfo.CreateNoWindow = true;
            proc.Start();
            proc.WaitForExit();
            Process proc1 = new Process();
            string top1 = "netsh.exe";
            proc1.StartInfo.Arguments = "Advfirewall set publicprofile state off";
            proc1.StartInfo.FileName = top1;
            proc1.StartInfo.UseShellExecute = false;
            proc1.StartInfo.RedirectStandardOutput = true;
            proc1.StartInfo.CreateNoWindow = true;
            proc1.Start();
            proc1.WaitForExit();
            Console.Clear();
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Add Firewall 80 TCP...");
            Process proc2 = new Process();
            string top2 = "netsh.exe";
            proc2.StartInfo.Arguments = "firewall add portopening TCP 80 80";
            proc2.StartInfo.FileName = top2;
            proc2.StartInfo.UseShellExecute = false;
            proc2.StartInfo.RedirectStandardOutput = true;
            proc2.StartInfo.CreateNoWindow = true;
            proc2.Start();
            proc2.WaitForExit();
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall 80 TCP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Port GTPS (Default = ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("17091");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("): ");
            string portgtps1 = Console.ReadLine();
            int portgtps = int.Parse(portgtps1);
            Console.Clear();
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall 80 TCP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Port GTPS (Default = ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("17091");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("): " + portgtps + "\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Add Firewall " + portgtps + " UDP...");
            Process proc3 = new Process();
            string top3 = "netsh.exe";
            proc3.StartInfo.Arguments = "firewall add portopening TCP " + portgtps + " " + portgtps;
            proc3.StartInfo.FileName = top2;
            proc3.StartInfo.UseShellExecute = false;
            proc3.StartInfo.RedirectStandardOutput = true;
            proc3.StartInfo.CreateNoWindow = true;
            proc3.Start();
            proc3.WaitForExit();
            Console.Clear();
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall 80 TCP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Port GTPS (Default = ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("17091");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("): " + portgtps + "\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall " + portgtps + " UDP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Finding XAMPP...\n");
            if (!Directory.Exists("C:\\xampp\\htdocs"))
            {
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Write("-");
                Console.ResetColor();
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] XAMPP Not Found! Please Download XAMPP\nPress any key to continue . . . ");
                Console.ReadKey();
                Process.Start("https://www.apachefriends.org/download.html");
                Environment.Exit(0);
                return;
            }
            Console.Clear();
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall 80 TCP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Port GTPS (Default = ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("17091");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("): " + portgtps + "\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall " + portgtps + " UDP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] XAMPP has been found! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Creating server_data.php...");
            Directory.CreateDirectory(@"C:\xampp\htdocs\growtopia");
            using (System.IO.StreamWriter sdata = new System.IO.StreamWriter(@"C:\xampp\htdocs\growtopia\server_data.php", false))

            {
                string ipvps = new WebClient().DownloadString("http://ipinfo.io/ip").Replace("\n", "");
                sdata.WriteLine("server|" + ipvps);
                sdata.WriteLine("port|" + portgtps);
                sdata.WriteLine("type|1");
                sdata.WriteLine("#maint|Server Maintenance");
                sdata.WriteLine("");
                sdata.WriteLine("beta_server|127.0.0.1");
                sdata.WriteLine("beta_port|17091");
                sdata.WriteLine("");
                sdata.WriteLine("beta_type|1");
                sdata.WriteLine("meta|localhost");
                sdata.Write("RTENDMARKERBS1001");
                sdata.Close();
            }
            Console.Clear();
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("GTPSAutoSet Created By GuckTube YT\n");
            Console.Write("This app can set your vps to can make GTPS WIth Easily\nPress any key to continue . . . \n\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] the Windows Firewall Defender has been Turned off! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall 80 TCP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Port GTPS (Default = ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("17091");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("): " + portgtps + "\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Firewall " + portgtps + " UDP has been Added! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] XAMPP has been found! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] server_data.php has been Created! ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("✓\n");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.Write("?");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] do you want to use Auto Hosts Maker? ");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            string selectmaker1 = Console.ReadLine();
            string selectmaker = selectmaker1.ToLower();
            if (selectmaker.Contains("Y"))
            {
                string current = Directory.GetCurrentDirectory();
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Creating Hosts...");
                using (System.IO.StreamWriter hosts = new System.IO.StreamWriter("server.host", false))

                {
                    string ipvps = new WebClient().DownloadString("http://ipinfo.io/ip").Replace("\n", "");
                    hosts.Write(ipvps + " growtopia1.com\n" + ipvps + " growtopia2.com");
                }
                Console.Write("\n");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Hosts file Path = " + current + "\n");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Hosts has been Created! ");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("✓\n");
            }

            if (selectmaker.Contains("y"))
            {
                string current = Directory.GetCurrentDirectory();
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Creating Hosts...");
                using (System.IO.StreamWriter hosts = new System.IO.StreamWriter("server.host", false))

                {
                    string ipvps = new WebClient().DownloadString("http://ipinfo.io/ip").Replace("\n", "");
                    hosts.Write(ipvps + " growtopia1.com\n" + ipvps + " growtopia2.com");
                }
                Console.Write("\n");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Hosts file Path = " + current + "\n");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("[");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("+");
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write("] Hosts has been Created! ");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write("✓\n");
            }
            Console.ResetColor();
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("+");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] Your vps Has Been Setted!\n");
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write("!");
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("] WARNING: If you use Microsoft Azure VPS = You Must add firewall port from portal.azure.com\nPress any key to continue . . . ");
            Console.ResetColor();
            Console.ReadKey();
        }
    }
}
